name: Run Pylint

on:
  push:
    paths:
      - "fastapi/weather_app/**/*.py"
      - ".github/workflows/pylint.yml"
  pull_request:
    paths:
      - "fastapi/weather_app/**/*.py"
      - ".github/workflows/pylint.yml"

jobs:
  pylint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: "3.12" }

      - name: Install Poetry dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        working-directory: fastapi
        run: poetry install

      - name: Run Pylint check
        working-directory: fastapi
        run: poetry run pylint --fail-under=10 **/*.py
