name: Run Pylint

on:
  push:
    paths:
      - "fastapi/weather_app/**/*.py"
      - ".github/workflows/pylint.yml"
  pull_request:
    paths:
      - "fastapi/weather_app/**/*.py"
      - ".github/workflows/pylint.yml"

jobs:
  pylint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: fastapi/poetry.lock

      - name: Install Poetry dependencies
        working-directory: fastapi
        run: poetry install

      - name: Run Pylint check
        working-directory: fastapi
        run: poetry run pylint --fail-under=10 **/*.py
