name: Run Pytest

on:
  push:
    paths:
      - "fastapi/weather_app/**/*.py"
      - ".github/workflows/pytest.yml"
  pull_request:
    paths:
      - "fastapi/weather_app/**/*.py"
      - ".github/workflows/pytest.yml"

jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: "3.12" }

      - name: Install Poetry dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        working-directory: fastapi
        run: poetry install

      - name: Run Pytest tests
        working-directory: fastapi
        run: poetry run pytest
