name: Run Pytest

on:
  push:
    paths:
      - "fastapi/weather_app/**/*.py"
      - ".github/workflows/pytest.yml"
  pull_request:
    paths:
      - "fastapi/weather_app/**/*.py"
      - ".github/workflows/pytest.yml"

jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: fastapi/poetry.lock

      - name: Install Poetry dependencies
        working-directory: fastapi
        run: poetry install

      - name: Run Pytest tests
        working-directory: fastapi
        run: poetry run pytest
